### PR TITLE
date formatting fix for query results

### LINKED ISSUE #2663: Runtime: Return `DATE` values as strings instead of timestamps for toplists
See context in [this Slack thread](https://rilldata.slack.com/archives/CTZ8XBQ85/p1686961827784559).

We should be able to make this change in `runtime/queries/metricsview.go:rowsToData`. The `rows` value returned there contains type info for the returned values.

Proposed task list:

- [ ] Update the `rowsToData` function to return result values of type `DATE` as a string in `YYYY-MM-DD` format instead of as a timestamp-formatted string

### PR DESCRIPTION
**Pull request by k-anshul**
closes #2663

### CODE REVIEW

File: runtime/pkg/pbutil/pbutil.go [hunk 1]
```diff
@@ -95,32 +104,48 @@ func ToValue(v any) (*structpb.Value, error) {
...
+			if err != nil {
+				return nil, err
+			}
 		}
-		var err error
-		x.Fields[k], err = ToValue(v)
-		if err != nil {
-			return nil, err
+	} else {
+		for _, f := range t.Fields {
```
Comment (k-anshul) [inline runtime/pkg/pbutil/pbutil.go:122]: Is it guaranteed that the size of fields will always be equal to size of `v`. I see a check for size in `safeFieldType`

**Review by begelundmuller — APPROVED** [review]

File: runtime/pkg/pbutil/pbutil.go (hunk 1 above)
Comment (begelundmuller) [reply runtime/pkg/pbutil/pbutil.go:122]: It's generally the case, but not if fields have been removed from the schema (like in the time series APIs in this PR). 

The size check in `safeFieldType` is just to be extra safe.
