### PR TITLE
Prevent overlapping success/error notifications in users invite

### LINKED ISSUE #6655: Confusing notifications when a user invite fails
Address https://rilldata.slack.com/archives/C04AGHL77PS/p1739281194428469

"If a user invite fails in UI it shows the success notification on top of failure one. Confused me until I saw the network tab. Also seems to mark a failed invite as success."

- [x] Revisit success/error notifactions when inviting a user

### PR DESCRIPTION
**Pull request by lovincyrus**
Closes #6655

- Fixed duplicate notifications by removing individual success/error messages from handleCreate and only showing consolidated notifications after all invites are processed
- Fixed failed invites being marked as successful by properly tracking failed/succeeded invites separately and only adding to succeeded array when the invite actually succeeds
- Prevent notification stacking by showing only one at a time

To test this PR by setting the org invite limit, `rill sudo quota set --org <org_name> --outstanding-invites 0`

https://github.com/user-attachments/assets/99cede5d-411c-4a97-8835-a5ada2b1667a

**Checklist:**
- [ ] Covered by tests
- [x] Ran it and it works as intended
- [x] Reviewed the diff before requesting a review
- [ ] Checked for unhandled edge cases
- [x] Linked the issues it closes
- [x] Checked if the docs need to be updated
- [ ] Intend to cherry-pick into the release branch
- [ ] I'm proud of this work!

### CODE REVIEW

File: web-admin/src/features/organizations/users/AddUsersDialog.svelte [hunk 1]
```diff
@@ -98,37 +94,53 @@
...
+            await handleCreate(email, values.role, isSuperUser);
+            succeeded.push(email);
+          } catch (error) {
+            failed.push(email);
+            console.error("Error adding user to organization", error);
+          }
+        }
+
+        // Only show success notification if any invites succeeded
+        if (succeeded.length > 0) {
```
Comment (AdityaHegde) [inline web-admin/src/features/organizations/users/AddUsersDialog.svelte:120]: We need a case where both `succeeded.length > 0` and `failed.length > 0` are true. Otherwise there will still be overlapping notifications.

File: web-admin/src/features/organizations/users/AddUsersDialog.svelte [hunk 2]
```diff
@@ -98,37 +94,53 @@
...
-        eventBus.emit("notification", {
-          type: "success",
-          message: `Invited ${succeeded.length} ${succeeded.length === 1 ? "person" : "people"} as ${values.role}`,
-        });
-
-        if (errored) {
+        const failed = [];
+
+        // Process invites sequentially to maintain order
+        for (const email of emails) {
```
Comment (AdityaHegde) [inline web-admin/src/features/organizations/users/AddUsersDialog.svelte:109]: Hmmm not sure doing this serially is a good idea. There could a huge list of invitees leading to a slow experience.

How about keeping the `Promise.all` but use the index in the `emails.map` to maintain order?
```
// pre-allocate
succeeded = new Array(emails.length).fill(undefined)
failed = ...

await Promise.all(
  emails.map(async (email, i) => {
    try {
      ...
      succeeded[i] = email
    } catch (err) {
      failed[i] = err
    }
  })
)

// remove empty values
succeeded = succeeded.filter(Boolean)
failed = failed.filter(Boolean)
```

File: web-admin/src/features/organizations/users/AddUsersDialog.svelte (hunk 1 above)
Comment (lovincyrus) [reply web-admin/src/features/organizations/users/AddUsersDialog.svelte:120]: https://github.com/rilldata/rill/pull/6658/files#r1954936512

Comment (lovincyrus) [reply web-admin/src/features/organizations/users/AddUsersDialog.svelte:120]: Made the change directly in NotificationCenter since there shouldn't ever be overlapping notifications in general when it's not supported

**Review by AdityaHegde — APPROVED** [review]
