### PR TITLE
fix: reconnect to a different github failing with `remote already exists`

### LINKED ISSUE #6468: [Regression] Unable to reconnect to different Repository from UI
**Describe the bug**
After disconnecting from remote A in the UI, and trying to connect remote B. The following error occurs 
`failed to create remote: remote already exists`

**To Reproduce**
1. Connect to remote A via UI.
2. Disconnect via the UI.
3. Try to reconnect a different remote to write RC projects to
4. Error occurs

**Expected behavior**
Disconnecting from a repository should remove any git parameters from the existing deployment to allow RC project to connect to new repo.

**Screenshots**
Image
Image

**Additional context**
Prod and release-53

### PR DESCRIPTION
**Pull request by AdityaHegde**
closes #6468

`.git` folder was getting added to the archive after disconnecting from github. `drivers.IsIgnored` expects a leading `/`.

Also there could already be projects with the `.git` folder. So handle this case when reconnecting to a new repo.

### CODE REVIEW

File: admin/server/github.go [hunk 1]
```diff
@@ -1053,7 +1053,20 @@ func (s *Server) pushToGit(ctx context.Context, copyData func(projPath string) e
 	}
 
 	if empty {
-		// we need to add a remote if the repo was completely empty
+		remote, err := ghRepo.Remote("origin")
```
Comment (k-anshul) [inline admin/server/github.go:1056]: Why not simply delete the `.git` folder ?

Comment (AdityaHegde) [reply admin/server/github.go:1056]: Since we are making a commit just before it would remove all of that.

Comment (AdityaHegde) [reply admin/server/github.go]: Ignoring .git during untar. So this is not needed.

File: runtime/pkg/archive/archive.go [hunk 2]
```diff
@@ -172,11 +172,18 @@ func untar(src, dest string) error {
 			return err
 		}
 
+		// nolint:gosec // adding the '..' check here is still triggering gosec for GSC-G305
+		if strings.Contains(header.Name, "..") ||
```
Comment (begelundmuller) [inline runtime/pkg/archive/archive.go:176]: How does `..` end up in the paths here?

Comment (AdityaHegde) [reply runtime/pkg/archive/archive.go:176]: Right now it cant. But if we allow users to upload their own archives then it can lead to this security issue. So better to have this safeguard now.

https://app.deepsource.com/directory/analyzers/go/issues/GSC-G305
https://security.snyk.io/research/zip-slip-vulnerability

Comment (k-anshul) [reply runtime/pkg/archive/archive.go:176]: Why don't we just delete `.git` folder after untar in `Download` since this is just to circumnavigate an older issue?
That way we don't need to worry about the security issue as well ?

Comment (AdityaHegde) [reply runtime/pkg/archive/archive.go:176]: Since we are untaring to a location it will overwrite exiting `.git`. Then removing the `.git` will remove anything we did before the untar. This could be an issue if we are pushing to a previously populated repo.

So it is better to ignore it here.

**Review by k-anshul — APPROVED** [review]

File: runtime/pkg/archive/archive.go (hunk 2 above)
Comment (AdityaHegde) [reply runtime/pkg/archive/archive.go:176]: Removing the `..` check since `sanitizeArchivePath` already does it. But the linter is not smart enough to know this so we still need the `nolint`
