### PR TITLE
Human readable relative time

### LINKED ISSUE #6416: Update relative time in Environment Variable table to display better human-readable time unit format
**Describe the bug**
Currently, I'm seeing that time units are abbreviated which makes it difficult at first glance to infer
Screenshot 2025-01-14 at 8 56 49 AM

**To Reproduce**
1. Go to Project Settings > Environment Variables > Find a project that has Env Variables configured more than 24 hours ago
2. Look at the Activity column and you'll see that right now Day = D, Month = M, Year = Y

**Expected behavior**
From the spec, the desired time unit format is:

- **Within 1 minute:**
    - Display: "just now"
- **1 minute to 59 minutes:**
    - Display: "X minutes ago" (rounded to the nearest minute)
- **1 hour to 23 hours:**
    - Display: "X hours ago" (rounded to the nearest hour)
- **1 day to 6 days:**
    - Display: "X days ago" (rounded to the nearest day)
- **1 week to 4 weeks:**
    - Display: "X weeks ago" (rounded to the nearest week)
- **1 month to 11 months:**
    - Display: "X months ago" (rounded to the nearest month)
- **1 year and beyond:**
    - Display: "X years ago" (rounded to the nearest year)

### PR DESCRIPTION
**Pull request by lovincyrus**
Human readable date time, closes #6416. Added a `TimeAgo` component to exhibit similar datetime behavior used in https://github.com/nmn/react-timeago

https://github.com/user-attachments/assets/94d6839f-cc0d-43c3-9f1c-eb51ac3f7e0e

### CODE REVIEW

**Comment by ericokuma** [comment]
Screenshot 2025-02-07 at 3 19 55 PM

Can we capitalize `just now` so that it's `Just now`?

File: web-admin/src/features/projects/environment-variables/TimeAgo.svelte [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+    }
+  }
+
+  function resetInterval(newInterval: number) {
+    if (interval) clearInterval(interval);
+    interval = setInterval(updateTimeAgo, newInterval);
+  }
+
+  // Reactively update whenever `datetime` changes
+  $: updateTimeAgo();
```
Comment (ericpgreen2) [inline web-admin/src/features/projects/environment-variables/TimeAgo.svelte:44]: This doesn't look like a statement that's reactive to `datetime`, since `datetime` isn't a parameter to the function. IMO a pure function would be more clear.

**Review by ericpgreen2 — APPROVED** [review]
