### PR TITLE
fix: various time ranges issues in alerts

### LINKED ISSUE #6447: Alerts dialog issues
From [this Slack message](https://rilldata.slack.com/archives/CTZ8XBQ85/p1736347418250419):
> The Alerts dialog has some funky behaviour that can block the user from using it, especially if you split the data by a high cardinality field.
>  - For certain time ranges, the metric total doesn't match the real figure when certain time ranges are selected. I tried Today, Yesterday, Last 1 Week.
>  - The sample figures are sorted in ascending order, which means for high cardinality fields you only see a bit of the long tail instead of the largest dimensions. Descending order with significant values first would work better.
>     - Also, when trying to set criteria, it means that no data appear to meet even a low threshold
>  - The options to alert based on changes are greyed out, even when starting with a comparison period selected
>  - Not a bug but: it would be useful to be able to change the time period from within the alert dialog, especially when reacting to the tooltip if you started the dialog without a comparison period selected..
>  
> Tested on [this dashboard](https://ui.rilldata.com/demo/rill-openrtb-prog-ads/explore/bids_explore?view=pivot&tr=rill-PDC&compare_tr=rill-PP&grain=hour&compare_dim=campaign_name&rows=campaign_name&cols=overall_spend).

### PR DESCRIPTION
**Pull request by AdityaHegde**
closes #6447

- [x] Fix time zone not getting passed through for metrics aggregation query.
- [x] Sort preview by descending.
- [x] Fix time comparison not enabled in alert even when enabled while in pivot view.

### CODE REVIEW

File: web-common/src/features/dashboards/time-controls/time-range-mappers.ts [hunk 1]
```diff
@@ -82,10 +85,11 @@ export function mapComparisonTimeRange(
   dashboardState: MetricsExplorerEntity,
   timeControlState: TimeControlState,
   timeRange: V1TimeRange | undefined,
+  forceTimeComparison: boolean,
```
Comment (ericpgreen2) [inline web-common/src/features/dashboards/time-controls/time-range-mappers.ts:88]: I'm not following, why is this necessary? This feels like something that should be fixed upstream

Comment (AdityaHegde) [reply web-common/src/features/dashboards/time-controls/time-range-mappers.ts:88]: This fixes the case where both time and dimension comparison is enabled. For alerts we should add time comparison in either cases.

File: runtime/queries/metricsview_aggregation.go [hunk 2]
```diff
@@ -329,6 +332,9 @@ func (q *MetricsViewAggregation) rewriteToMetricsViewQuery(export bool) (*metric
 		res.IsoDuration = q.ComparisonTimeRange.IsoDuration
 		res.IsoOffset = q.ComparisonTimeRange.IsoOffset
 		res.RoundToGrain = metricsview.TimeGrainFromProto(q.ComparisonTimeRange.RoundToGrain)
+		if q.ComparisonTimeRange.TimeZone != "" && qry.TimeZone == "qry.TimeZone" {
```
Comment (begelundmuller) [inline runtime/queries/metricsview_aggregation.go:335]: Why would it be `"qry.TimeZone"` as a string? It's expected to be an IANA time zone code.

Also since we don't support different time zones in `qry.TimeZone`, IMO it should return an error if `q.TimeRange.TimeZone` and `q.ComparisonTimeRange.TimeZone` specify different time zones.

**Review by begelundmuller — CHANGES_REQUESTED** [review]

File: web-common/src/features/dashboards/time-controls/time-range-mappers.ts (hunk 1 above)
Comment (ericpgreen2) [reply web-common/src/features/dashboards/time-controls/time-range-mappers.ts:88]: Instead, can we delete line 92 altogether? I'm not immediately seeing why `selectedComparisonDimension` should remove the comparison time range.

**Review by begelundmuller — APPROVED** [review]
Backend looks good now

File: web-common/src/features/dashboards/time-controls/time-range-mappers.ts (hunk 1 above)
Comment (AdityaHegde) [reply web-common/src/features/dashboards/time-controls/time-range-mappers.ts:88]: Hmmm I dont see any issue with that. It was just some old code to remove time comparison when dimension comparison is enabled.

@mindspank Ok to remove this check? It affects scheduled reports for TDD and dimension table.

Comment (mindspank) [reply web-common/src/features/dashboards/time-controls/time-range-mappers.ts:88]: Should be fine

**Review by ericpgreen2 — APPROVED** [review]
