### PR TITLE
Fix issues around unnest in dashboard

### LINKED ISSUE #4691: Fix: Having multiple unnest dimensions shows a blank screen in preview
Having multiple unnest dimensions shows a blank screen in preview, the metrics view schema query errors out.
Add this to a dashboard created from the AdBids.csv file source,
```
  - label: Domain Parts
    name: domain_parts
    expression: "string_split(domain, '.')"
    unnest: true
  - label: Domain Parts 2
    name: domain_parts_2
    expression: "string_split(domain, '.')"
    unnest: true
```
Error,
```
Binder Error: Duplicate alias "tbl" in query!
```

Another issue is that this error is not caught in validation. Validation code doesnt honour the unnest boolean.

### PR DESCRIPTION
**Pull request by AdityaHegde**
closes #4691 , #4686

- [x] Fix multiple dimensions having unnest breaking certain queries.
- [x] Update validation to check for unnest

### CODE REVIEW

File: runtime/drivers/olap.go [hunk 1]
```diff
@@ -182,3 +183,36 @@ func (d Dialect) EscapeTable(db, schema, table string) string {
...
+	}
+
+	return sel, fmt.Sprintf(`, LATERAL UNNEST(%s) %s(%s)`, dim.Expression, unnestTableName, unnestColName)
+}
+
+func tempName(prefix string) string {
+	return prefix + strings.ReplaceAll(uuid.New().String(), "-", "")
+}
+
+func (d Dialect) MetricsViewDimensionExpression(dimension *runtimev1.MetricsViewSpec_DimensionV2) string {
```
Comment (begelundmuller) [inline runtime/drivers/olap.go:208]: Is it correct to call this directly? Could seem like unnest is not handled in those places where it's used directly.

Comment (AdityaHegde) [reply runtime/drivers/olap.go:208]: Good point. I just renamed it to export the method. Lemme take a look at its usages.

Comment (AdityaHegde) [reply runtime/drivers/olap.go:204]: In all the cases it is used in expressions and not select so it wont be a problem. We can do a follow up to update one usage in the metrics view comparison query for druid as a follow up.

**Review by begelundmuller — APPROVED** [review]
