### PR TITLE
disable preview button when explore resource is reconciling

### LINKED ISSUE #5957: Preview button should be disabled when dashboards are reconciling
Bug report: https://rilldata.slack.com/archives/C02T907FEUB/p1729646001749779

### PR DESCRIPTION
**Pull request by briangregoryholmes**
closes #5957

### CODE REVIEW

File: web-common/src/features/workspaces/ExploreWorkspace.svelte [hunk 1]
```diff
@@ -56,7 +64,7 @@
     <PreviewButton
       slot="cta"
       href="/explore/{exploreName}"
-      disabled={allErrors.length > 0}
+      disabled={allErrors.length > 0 || resourceIsReconciling}
```
Comment (ericpgreen2) [inline web-common/src/features/workspaces/ExploreWorkspace.svelte:67]: Mind adding a tooltip to say why the button is disabled?

**Review by ericpgreen2 — APPROVED** [review]
