### PR TITLE
User-friendly error instead of "Out of buffer" on ingesting TIME column from Snowflake

### LINKED ISSUE #3604: Out of buffer on ingesting TIME column from Snowflake
time32/64 types are [not supported](https://github.com/duckdb/duckdb/issues/1742) by DuckDB
Fail fast with a user-friendly error instead of "Out of buffer"

### PR DESCRIPTION
**Pull request by esevastyanov**
Closes #3604

### CODE REVIEW

File: runtime/drivers/snowflake/sql_store.go [hunk 1]
```diff
@@ -159,6 +160,11 @@ func (f *fileIterator) Next() ([]string, error) {
 
 	// common schema
 	schema := (*firstBatch)[0].Schema()
+	for _, f := range schema.Fields() {
+		if f.Type.ID() == arrow.TIME32 || f.Type.ID() == arrow.TIME64 {
+			return nil, fmt.Errorf("TIME type isn't supported, consider excluding it")
```
Comment (begelundmuller) [inline runtime/drivers/snowflake/sql_store.go:165]: Consider adding the column name as well, e.g. `"TIME data type (column %q) is not currently supported, consider excluding it or casting it to another data type"`

**Review by begelundmuller — APPROVED** [review]
