### PR TITLE
fix: explore page when it is reconciled for the 1st time

### LINKED ISSUE #6668: Project deployment: first dashboard load has issues initializing state
[Jam recording](https://jam.dev/c/d4d9a0b3-176e-4827-bd51-4b30bc2cb5a0)

To reproduce:
1. Redeploy a project: `rill project hibernate --redeploy --force --project <project-name>`
2. Navigate to a dashboard
3. See the loading "hang tight" message
4. When the dashboard resolves (for the first time), the page will go blank with an error message in the console

I started tracking this down, and it seems like the dashboard's client-side state (the `MetricsExplorerEntity` object) has not been properly initialized.

### PR DESCRIPTION
**Pull request by AdityaHegde**
closes #6668

**Checklist:**
- [ ] Covered by tests
- [x] Ran it and it works as intended
- [x] Reviewed the diff before requesting a review
- [x] Checked for unhandled edge cases
- [x] Linked the issues it closes
- [ ] Checked if the docs need to be updated
- [x] Intend to cherry-pick into the release branch
- [ ] I'm proud of this work!

### CODE REVIEW

File: web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte [hunk 1]
```diff
@@ -118,6 +118,21 @@
...
+  let reconcilingForFirstTime: boolean | undefined;
+  $: if ($explore.isSuccess) {
+    const newReconcilingForFirstTime = isDashboardReconcilingForFirstTime(
+      $explore.data,
+    );
+    if (
+      reconcilingForFirstTime !== undefined &&
+      newReconcilingForFirstTime !== undefined &&
+      reconcilingForFirstTime !== newReconcilingForFirstTime
+    ) {
```
Comment (ericpgreen2) [inline web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte:131]: An explanatory variable would make this more clear. Also, would this simpler condition work?
```
const justFinishedFirstReconcile = reconcilingForFirstTime === true && newReconcilingForFirstTime === false
if (justFinishedFirstReconcile) void invalidate(`explore:${exploreName}`);
```

```

File: web-common/src/features/dashboards/url-state/DashboardURLStateSync.svelte [hunk 2]
```diff
@@ -174,7 +174,13 @@
   });
 
   async function handleExploreInit(isManualUrlChange: boolean) {
-    if (!exploreSpec || !metricsSpec || initializing) return;
+    if (
+      !exploreSpec ||
+      !metricsSpec ||
+      initializing ||
+      exploreStateFromYAMLConfig.activePage === undefined
+    )
```
Comment (ericpgreen2) [inline web-common/src/features/dashboards/url-state/DashboardURLStateSync.svelte:182]: An explanatory variable could help here too. It should help explain to someone how/why this condition would ever need to be extended in the future.

**Review by ericpgreen2 — APPROVED** [review]

**Comment by ericpgreen2** [comment]
Also, can you please cherry-pick this onto the v56 release branch?

File: web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte (hunk 1 above)
Comment (AdityaHegde) [reply web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte:131]: Sure adding a variable. That new condition wont work when switching from `false` to `true` when redeployed. Probably good to keep it consistent.
